feat: airTransportRatio should depend on durability
MTES-MCT/ecobalyse pull request #757
Opened 2024-09-17 12:36 UTC by vjousse

[Notion card](https://www.notion.so/Adapter-la-part-de-transport-en-avion-automatiquement-en-fonction-de-la-durabilit-76a7514bedb44d3298f401d69f09672f)

2024-09-17 13:40 UTC, n1k0 approved these changes
The code looks good to me and the implementation seems to work as expected by the spec.

2024-09-17 13:40 UTC, n1k0 commented on src/Data/Textile/Simulator.elm
> +                            iSEuropeOrTurquey =
Nit: isEuropeOrTurquey (lower s)

Also, it's `Turkey` or `Türkiye`

2024-09-17 13:40 UTC, n1k0 commented on src/Data/Textile/Simulator.elm
> +                                country.zone == Zone.Europe || country.code == Country.codeFromString "TR"
Also, how about moving this to `Data.Country` as a helper?

2024-09-17 13:40 UTC, n1k0 commented on src/Data/Textile/Simulator.elm
> +                                    Split.fromFloat 0.33 |> Result.withDefault step.airTransportRatio
We may want to introduce `Split.third` here

2024-09-17 13:40 UTC, n1k0 commented on src/Data/Textile/Simulator.elm
> +                                    Split.full
Nit: Probably matter of taste but I'd find this block more readable using plain old if statements:

```suggestion
                        if inputs.airTransportRatio /= Nothing then
                            -- User-provided value always takes precedence
                            step.airTransportRatio

                        else if country.zone == Zone.Europe || country.code == Country.codeFromString "TR" then
                            -- If Making country is Europe or Turquey, airTransportRatio is always 0
                            Split.zero

                        else if Unit.floatDurabilityFromHolistic simulator.durability >= 1 then
                            -- Durable garments outside of Europe and Turquey
                            Split.fromFloat 0.33
                                |> Result.withDefault step.airTransportRatio

                        else
                            Split.full
```

2024-09-17 14:30 UTC, n1k0 reviewed
I realize we could add a test ensuring that the simulator behaves accordingly to provided inputs and defaults regarding the air transport ratio

2024-09-17 14:30 UTC, n1k0 commented on src/Data/Country.elm
> +    country.zone == Zone.Europe || country.code == codeFromString "TR"
I swear I added a comment about s/iSEuropeOrTurkey/isEuropeOrTurkey here 🤷

2024-09-17 15:44 UTC, n1k0 requested changes
Hold on landing this patch, after a more careful review and toying around with the code, I realize we always override the default country airTransportRatio value when it's been used in `updateFromInputs` in `Step.elm` ([here](https://github.com/MTES-MCT/ecobalyse/blob/master/src/Data/Textile/Step.elm#L351-L352)). Ideally we should handle the airTransportRatio in a single place when we have the final durability as you have done in the patch, and so remove the assignment in `Step.elm`. I've asked what we should we do with default coutry airTransportRatio to POs.

2024-09-17 16:08 UTC, vjousse commented
I'm holding tight :smile:

2024-09-18 05:33 UTC, n1k0 commented
I've pushed 90948a1d560c1eeeaec4c60ea34656ed3a7e18a0 which fallback on country air transport default when no condition is match. Let's wait for POs to know what they think.

2024-09-18 14:19 UTC, vjousse commented
> I realize we could add a test ensuring that the simulator behaves accordingly to provided inputs and defaults regarding the air transport ratio

Done in https://github.com/MTES-MCT/ecobalyse/pull/757/commits/f5e155b9d844ea3e1e148010f3b4f54c49013dd3

2024-09-19 07:55 UTC, n1k0 commented
@vjousse can we remove the `airTransportRatio` data from the `countries.json` database and from the `Country` type?

2024-09-19 08:25 UTC, vjousse commented
> @vjousse can we remove the `airTransportRatio` data from the `countries.json` database and from the `Country` type?

Done in https://github.com/MTES-MCT/ecobalyse/pull/757/commits/5b0c9fd5b59978c4abfae87480ef068f11ff3cf4

2024-09-19 08:33 UTC, vjousse commented
Hmmmm should we completely remove the information from the country tab in the explorer?

2024-09-19 10:43 UTC, n1k0 commented
> Hmmmm should we completely remove the information from the country tab in the explorer?

Not, we still want to expose all the supported country codes.

2024-09-20 06:55 UTC, n1k0 approved these changes
I took the liberty to fix the remaining conflicts and compilator issues. This is ready to land imho.

2024-09-23 08:01 UTC, vjousse commented
Approved by Pascal on [mattermost](https://mattermost.incubateur.net/fabnum-mte/pl/y7im6no4b7g33g49dyp3syd35a)

2024-09-23 08:01 UTC, merged